[package]
name = "strategy"
type = "bin"
authors = ["masaun"]
compiler_version = ">=1.0.0"
version = "0.0.1"

[dependencies]
# Poseidon hash function for Noir
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }

# ZK-Kit: Merkle tree libarry
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
